-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 10:06:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`blogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_actualizacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administradores_blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administradores_blog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `blog_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  INDEX `fk_blogs_has_usuarios_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_blogs_has_usuarios_blogs1_idx` (`blog_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_blogs_has_usuarios_blogs1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `mydb`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blogs_has_usuarios_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NULL,
  `fecha_publicacion` DATETIME NULL,
  `fecha_modificacion` DATETIME NULL,
  `blog_id` INT NOT NULL,
  `administrador_blog_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publicaciones_blogs1_idx` (`blog_id` ASC) VISIBLE,
  INDEX `fk_publicaciones_administradores_blog1_idx` (`administrador_blog_id` ASC) VISIBLE,
  CONSTRAINT `fk_publicaciones_blogs1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `mydb`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publicaciones_administradores_blog1`
    FOREIGN KEY (`administrador_blog_id`)
    REFERENCES `mydb`.`administradores_blog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comentario` TEXT NULL,
  `fecha_publicacion` DATETIME NULL,
  `fecha_modificacion` DATETIME NULL,
  `usuario_id` INT NOT NULL,
  `publicacion_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `publicacion_id`),
  INDEX `fk_comentarios_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_comentarios_publicaciones1_idx` (`publicacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_publicaciones1`
    FOREIGN KEY (`publicacion_id`)
    REFERENCES `mydb`.`publicaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `fecha_conexion` DATETIME NULL,
  `fecha_desconexion` DATETIME NULL,
  `IP_adress` VARCHAR(50) NULL,
  `blog_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visitas_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_visitas_blogs1_idx` (`blog_id` ASC) VISIBLE,
  CONSTRAINT `fk_visitas_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visitas_blogs1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `mydb`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
